#// Add the Ubuntu Toolchain PPA.

RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update

#// Install packages that comprise build-essential, but replace compilers with 4.8.
#// http://packages.ubuntu.com/precise/build-essential

RUN apt-get install -y dpkg-dev gcc-4.8 g++-4.8 libc6-dev make

#// RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
#// RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
