FROM ubuntu:12.10
#include("baselines/Maintainer")

## A means of making sure the Docker image cache gets invalidated
## every once in a while, if you need to completely
## rebuild things. 
##
## Also possible with `docker --no-cache`
## 
## Reference: http://crosbymichael.com/dockerfile-best-practices.html

#include("packages/Dockerfile.enable-apt-cache")
#include("baselines/Dockerfile.update-upgrade")
